#!/bin/bash
# Phacket - Simple Package Manager for Philo

echo "Welcome to Phacket! Please enter a package name, or input LIST for a list of packages:"
read INPUT

if [ "$INPUT" = "LIST" ]; then
    wget https://raw.github.com/kwphil/phacket/main/list.txt -O temp.txt
    less -FX temp.txt
else
    wget https://raw.github.com/kwphil/phacket/main/$INPUT.txt -O temp.txt
    if [ ! -s "temp.txt" ]; then
        echo "Unknown package: $INPUT"
        exit 1
    fi
    
    ./phacket-install
fi

rm temp.txt