#!/bin/bash
# Phacket - Simple Package Manager for Philo
# Creator - KWPhil https://www.github.com/kwphil

usage() { echo "Usage: $0 [options] [package-name]\n
                Options: \n
                v: verbose: prints file changes
                "; exit 1; }


echo "Welcome to Phacket! Please enter a package name, or input LIST for a list of packages:"
read INPUT

while getopts ":s:p:" o; do
    case "${o}" in
        s)
            s=${OPTARG}
            

if [ "$INPUT" = "LIST" ]; then
    wget https://raw.github.com/kwphil/phacket/main/list.txt -O temp.txt
    less -FX temp.txt
else
    wget https://raw.github.com/kwphil/phacket/main/$INPUT.txt -O temp.txt
    if [ ! -s "temp.txt" ]; then
        echo "Unknown package: $INPUT"
        exit 1
    fi
    
    line_count=$(wc -l < temp.txt)
    ./bin/phacketDecode $line_count $INPUT
    exit $?
fi

rm temp.txt
exit 0