#!/bin/bash
# Philo Bash Shell - User interface for interacting with the C program Philo
# Creator - KWPhil

usage() {
  echo "Usage: $0 [-o filename] [-t]"
  echo "Options: "
  echo "-f - Attaches a file to compile"
  echo "-o - Creates a file with specified name to compile into"
  echo "-t - Compiles and runs, then removes the file automatically"
  echo "-p - Opens Phacket"
  exit 1
}

while getopts ":o:f:t:p" opt; do
  case $opt in
    o)
      if [ -f "$OPTARG"]
        bin/main.elf $FILE 1 "$OPTARG"
      else
        echo "Error: File '$OPTARG' not found."
        usage
      fi
      ;;
    f)
      $FILE=$OPTARG
      ;;
    t)
      bin/main.elf $FLIE 0
      ;;
    p)
      ./phacket
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

if [ $OPTIND -eq 1 ]; then
  usage
fi
