#!/bin/bash
# Philo Bash Shell - User interface for interacting with the C program Philo
# Creator - KWPhil

usage() {
  echo "Usage: $0 [-o filename] [-t]"
  exit 1
}

while getopts ":o:t" opt; do
  case $opt in
    o)
      if [ -f "$OPTARG" ]; then
        bin/main.elf 1 "$OPTARG"
      else
        echo "Error: File '$OPTARG' not found."
        usage
      fi
      ;;
    t)
      bin/main.elf 0
      ;;
    p)
      bin/phacket.elf
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

if [ $OPTIND -eq 1 ]; then
  usage
fi
